services:
  rs-gateway:
    container_name: rs-gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
      target: dev
    volumes:
      - ./gateway:/app/server
      - ./internal:/app/internal
      - ./proto:/app/proto
      - ./pb:/app/pb
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./magefiles:/app/magefiles
      - .env:/app/server/.env
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
      - ${GATEWAY_DEBUGGING_PORT}:${GATEWAY_DEBUGGING_PORT}
    working_dir: /app
    command: sh -c "/init/run.sh"
  rs-db:
    container_name: rs-db
    image: postgres:16
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
